version: "2"
run:
  issues-exit-code: 1
  tests: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - exhaustive
    - gocritic
    - gosec
    - importas
    - misspell
    - prealloc
    - promlinter
    - sloglint
    - sqlclosecheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - whitespace
    - zerologlint
  disable:
    - dupl
    - errname
    - revive
    - unparam
    - unused
    - wastedassign
  settings:
    errcheck:
      exclude-functions:
        - io.Copy
        - fmt.*
    exhaustive:
      ignore-enum-types: reflect.Kind|svc.Cmd
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: G107
    paths:
      - internal/ssh/?.*
      - internal/adapter
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/ssh/?.*
      - internal/adapter
      - third_party$
      - builtin$
      - examples$
