linters-settings:
  errcheck:
    exclude-functions:
      - io.Copy
      - fmt.*
      - (go.uber.org/zap/zapcore.ObjectEncoder).AddObject
      - (go.uber.org/zap/zapcore.ObjectEncoder).AddArray
  # gci:
  #   sections:
  #     - standard # Standard section: captures all standard packages.
  #     - default # Default section: contains all imports that could not be matched to another section type.
  #     - prefix(github.com/caddyserver/caddy/v2/cmd) # ensure that this is always at the top and always has a line break.
  #     - prefix(github.com/caddyserver/caddy) # Custom section: groups all imports with the specified Prefix.
  #   # Skip generated files.
  #   # Default: true
  #   skip-generated: true
  #   # Enable custom order of sections.
  #   # If `true`, make the section order the same as the order of `sections`.
  #   # Default: false
  #   custom-order: true
  exhaustive:
    ignore-enum-types: reflect.Kind|svc.Cmd
  misspell:
    locale: US

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - exhaustive
    - copyloopvar
    - gofmt
    - goimports
    - gofumpt
    - gosec
    - gosimple
    - ineffassign
    - importas
    - misspell
    - prealloc
    - promlinter
    - sloglint
    - sqlclosecheck
    - tenv
    - testableexamples
    - testifylint
    - tparallel
    - typecheck
    - unconvert
    - whitespace
    - zerologlint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - prealloc
    - unconvert
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - govet
    - staticcheck
    - gocritic
  disable:
    - unused
    - dupl
    - gci
    - unparam
    - errname
    - wastedassign
    - revive # TODO: Enable later and fix found issues

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

# output configuration options
output:
  formats:
    - format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  fix: true
  exclude-dirs:
   # this is inherited from github.com/gliderlabs/ssh and changes are incremental
    - internal/ssh/?.*
    - internal/adapter
  exclude-rules:
    - text: "G107" # G107: Url provided to HTTP request as taint input
      linters:
        - gosec
    # we're shelling out to known commands, not relying on user-defined input.
    # - text: "G204" # G204: Audit use of command execution
    #   linters:
    #     - gosec
