before:
  hooks:
    - sh -c 'rm -r ./custom-build || true'
    # hooks don't expand globs, so shell out
    - sh -c ./.github/scripts/build-env.sh
    - go mod edit -require=github.com/mohammed90/caddy-ssh@{{.Env.TAG}} ./custom-build/go.mod
    - sh -c 'cd custom-build && go mod tidy'

builds:
  - dir: custom-build
    binary: caddy-ssh
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - "amd64"

archives:
  - replacements:
      darwin: mac

checksum:
  name_template: "checksums.txt"
  algorithm: sha512

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: mohammed90
    name: caddy-ssh
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^docs?:"
      - "^readme:"
      - "^tests?:"
      - '^\w+\s+' # a hack to remove commit messages without colons thus don't correspond to a package
