name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # https://github.com/actions/setup-go/issues/491
  GOTOOLCHAIN: local

jobs:
  # From https://github.com/golangci/golangci-lint-action
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '~1.25.0'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 10m
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
